server.port: 5050
spring.ds.sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=Koutye;encrypt=false
spring.ds.sqlserver.username=jedma
spring.ds.sqlserver.password=Edma1995
spring.ds.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true


#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2022Dialect
#spring.jpa.database=sqlserver
spring.mvc.format.date=yyyy-MM-dd


#spring.main.allow-bean-definition-overriding=true

#spring.jpa.properties.hibernate.validator.apply_to_ddl=false

#spring.mvc.dispatch-options-request=true

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB


entitymanager.packages.to.scan=com.chrisnor.koutye

#pathUser=C:/Koutye_Folder/Users/
pathUser=C:/Users/lenovo/Documents/Projets/Angular/Koutye/src/assets/Koutye_Folder/Users/
pathUser2=C:/Users/lenovo/Documents/Projets/Ionic/Koutye/src/assets/Koutye_Folder/Users/
directoryPath=C:/Users/lenovo/Documents/Projets/Angular/Koutye/src/assets/Koutye_Folder/ImageApp/
directoryPath2=C:/Users/lenovo/Documents/Projets/Angular/Koutye/src/assets/Koutye_Folder/VideoApp/

pathAngular=C:/Users/lenovo/Documents/Projets/Angular/Koutye/src/
pathIonic=C:/Users/lenovo/Documents/Projets/Ionic/Koutye/src/

jwt.secret=YWTyoJ6q2bXB8fn2RPG6R3SQtZSkGHFeG5KzA4DcFcAxLK6k6yVf0wP3XHLdm+dJZRBm7nQ4p0uYkkEpAd27vw==

#configuration de srpring mail
spring.mail.host=smtp.gmail.com
#spring.mail.host=tombeauc@gmail.com 
spring.mail.port=587
spring.mail.username=app.koutye@gmail.com
#spring.mail.password=huesulkflunxzouh
spring.mail.password=hxhu nczc kgjo uqjg 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#fin de configuration de spring mail

#log4j with spring boot
logging.level.org.springframework.web=info
logging.level.org.hibernate=error
logging.file.name=C:/Koutye_Folder/KoutyeLog/appkoutye.log
expiration_Date=60
expiration_token=30

#log4j.rootLogger=DEBUG,stdout
#log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern=%d [%−5p] (%F:%M:%L) %m%n

######################################################################
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Koutye;encrypt=false
#spring.datasource.username=jedma
#spring.datasource.password=Edma1995
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.hibernate.ddl-auto=update

############################################################
#spring.security.oauth2.client.registration.github.clientId=Iv23livUqrYVZIKURszZ
#spring.security.oauth2.client.registration.github.clientSecret:

#url : https://console.cloud.google.com/home/dashboard?hl=fr&project=koutye-3fbda
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#spring.security.oauth2.client.registration.google.scope=profile, email
#spring.security.oauth2.client.registration.google.redirect-uri=

#url :
#authorization-code: 4/0AVG7fiRY4Hk8eHSLVlpRIlTBx2HDTZwn2uqQPC6UPO5z3myMCS1H6ce4N0r8SHdNCpSSsw
#security.oauth2.client.registration.facebook.clientId=
#security.oauth2.client.registration.facebook.clientSecret=
#security.oauth2.client.registration.facebook.redirectUri=

#url : https://github.com/settings/apps/koutye
#security.oauth2.client.registration.github.clientId=Iv23livUqrYVZIKURszZ
#security.oauth2.client.registration.github.clientSecret=0369b7f5f375d6e43edb02aa76b9c17610109ece
#security.oauth2.client.registration.github.redirectUri=
